// Lista zemalja/ekonomija koje World Bank (Svetska banka) prati u svojoj
// besplatnoj, javnoj bazi (World Bank Open Data, api.worldbank.org) — kod je
// njihov ISO-3166-1 alpha-3 kod, koji World Bank koristi direktno u svom API
// putu (/country/{code}/indicator/...). Nije moguće uživo povući ovu listu
// sa World Bank API-ja u ovom okruženju (nema mrežnog pristupa za to), pa je
// sastavljena iz opšteg znanja — može odstupati u par ivičnih slučajeva
// (sporne teritorije, mikro-države koje WB ne prati posebno).

export interface CountryEntry {
  code: string; // World Bank/ISO3 kod
  name: string; // naziv na srpskom
}

export const COUNTRIES: CountryEntry[] = [
  { code: "AFG", name: "Avganistan" },
  { code: "ALB", name: "Albanija" },
  { code: "DZA", name: "Alžir" },
  { code: "AGO", name: "Angola" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armenija" },
  { code: "AUS", name: "Australija" },
  { code: "AUT", name: "Austrija" },
  { code: "AZE", name: "Azerbejdžan" },
  { code: "BHS", name: "Bahami" },
  { code: "BHR", name: "Bahrein" },
  { code: "BGD", name: "Bangladeš" },
  { code: "BRB", name: "Barbados" },
  { code: "BLR", name: "Belorusija" },
  { code: "BEL", name: "Belgija" },
  { code: "BLZ", name: "Belize" },
  { code: "BEN", name: "Benin" },
  { code: "BTN", name: "Butan" },
  { code: "BOL", name: "Bolivija" },
  { code: "BIH", name: "Bosna i Hercegovina" },
  { code: "BWA", name: "Bocvana" },
  { code: "BRA", name: "Brazil" },
  { code: "BRN", name: "Brunej" },
  { code: "BGR", name: "Bugarska" },
  { code: "BFA", name: "Burkina Faso" },
  { code: "BDI", name: "Burundi" },
  { code: "KHM", name: "Kambodža" },
  { code: "CMR", name: "Kamerun" },
  { code: "CAN", name: "Kanada" },
  { code: "CPV", name: "Zelenortska Republika" },
  { code: "CAF", name: "Centralnoafrička Republika" },
  { code: "TCD", name: "Čad" },
  { code: "CHL", name: "Čile" },
  { code: "CHN", name: "Kina" },
  { code: "COL", name: "Kolumbija" },
  { code: "COM", name: "Komori" },
  { code: "COG", name: "Kongo (Republika)" },
  { code: "COD", name: "Kongo (DR)" },
  { code: "CRI", name: "Kostarika" },
  { code: "CIV", name: "Obala Slonovače" },
  { code: "HRV", name: "Hrvatska" },
  { code: "CUB", name: "Kuba" },
  { code: "CYP", name: "Kipar" },
  { code: "CZE", name: "Češka" },
  { code: "DNK", name: "Danska" },
  { code: "DJI", name: "Džibuti" },
  { code: "DOM", name: "Dominikanska Republika" },
  { code: "ECU", name: "Ekvador" },
  { code: "EGY", name: "Egipat" },
  { code: "SLV", name: "Salvador" },
  { code: "GNQ", name: "Ekvatorijalna Gvineja" },
  { code: "ERI", name: "Eritreja" },
  { code: "EST", name: "Estonija" },
  { code: "SWZ", name: "Esvatini" },
  { code: "ETH", name: "Etiopija" },
  { code: "FJI", name: "Fidži" },
  { code: "FIN", name: "Finska" },
  { code: "FRA", name: "Francuska" },
  { code: "GAB", name: "Gabon" },
  { code: "GMB", name: "Gambija" },
  { code: "GEO", name: "Gruzija" },
  { code: "DEU", name: "Nemačka" },
  { code: "GHA", name: "Gana" },
  { code: "GRC", name: "Grčka" },
  { code: "GRL", name: "Grenland" },
  { code: "GTM", name: "Gvatemala" },
  { code: "GIN", name: "Gvineja" },
  { code: "GNB", name: "Gvineja Bisao" },
  { code: "GUY", name: "Gvajana" },
  { code: "HTI", name: "Haiti" },
  { code: "HND", name: "Honduras" },
  { code: "HKG", name: "Hong Kong" },
  { code: "HUN", name: "Mađarska" },
  { code: "ISL", name: "Island" },
  { code: "IND", name: "Indija" },
  { code: "IDN", name: "Indonezija" },
  { code: "IRN", name: "Iran" },
  { code: "IRQ", name: "Irak" },
  { code: "IRL", name: "Irska" },
  { code: "ISR", name: "Izrael" },
  { code: "ITA", name: "Italija" },
  { code: "JAM", name: "Jamajka" },
  { code: "JPN", name: "Japan" },
  { code: "JOR", name: "Jordan" },
  { code: "KAZ", name: "Kazahstan" },
  { code: "KEN", name: "Kenija" },
  { code: "KIR", name: "Kiribati" },
  { code: "KOR", name: "Južna Koreja" },
  { code: "KWT", name: "Kuvajt" },
  { code: "KGZ", name: "Kirgistan" },
  { code: "LAO", name: "Laos" },
  { code: "LVA", name: "Letonija" },
  { code: "LBN", name: "Liban" },
  { code: "LSO", name: "Lesoto" },
  { code: "LBR", name: "Liberija" },
  { code: "LBY", name: "Libija" },
  { code: "LTU", name: "Litvanija" },
  { code: "LUX", name: "Luksemburg" },
  { code: "MAC", name: "Makao" },
  { code: "MDG", name: "Madagaskar" },
  { code: "MWI", name: "Malavi" },
  { code: "MYS", name: "Malezija" },
  { code: "MDV", name: "Maldivi" },
  { code: "MLI", name: "Mali" },
  { code: "MLT", name: "Malta" },
  { code: "MRT", name: "Mauritanija" },
  { code: "MUS", name: "Mauricijus" },
  { code: "MEX", name: "Meksiko" },
  { code: "MDA", name: "Moldavija" },
  { code: "MNG", name: "Mongolija" },
  { code: "MNE", name: "Crna Gora" },
  { code: "MAR", name: "Maroko" },
  { code: "MOZ", name: "Mozambik" },
  { code: "MMR", name: "Mjanmar" },
  { code: "NAM", name: "Namibija" },
  { code: "NPL", name: "Nepal" },
  { code: "NLD", name: "Holandija" },
  { code: "NZL", name: "Novi Zeland" },
  { code: "NIC", name: "Nikaragva" },
  { code: "NER", name: "Niger" },
  { code: "NGA", name: "Nigerija" },
  { code: "MKD", name: "Severna Makedonija" },
  { code: "NOR", name: "Norveška" },
  { code: "OMN", name: "Oman" },
  { code: "PAK", name: "Pakistan" },
  { code: "PAN", name: "Panama" },
  { code: "PNG", name: "Papua Nova Gvineja" },
  { code: "PRY", name: "Paragvaj" },
  { code: "PER", name: "Peru" },
  { code: "PHL", name: "Filipini" },
  { code: "POL", name: "Poljska" },
  { code: "PRT", name: "Portugal" },
  { code: "PRI", name: "Portoriko" },
  { code: "QAT", name: "Katar" },
  { code: "ROU", name: "Rumunija" },
  { code: "RUS", name: "Rusija" },
  { code: "RWA", name: "Ruanda" },
  { code: "WSM", name: "Samoa" },
  { code: "STP", name: "Sao Tome i Principe" },
  { code: "SAU", name: "Saudijska Arabija" },
  { code: "SEN", name: "Senegal" },
  { code: "SRB", name: "Srbija" },
  { code: "SYC", name: "Sejšeli" },
  { code: "SLE", name: "Sijera Leone" },
  { code: "SGP", name: "Singapur" },
  { code: "SVK", name: "Slovačka" },
  { code: "SVN", name: "Slovenija" },
  { code: "SLB", name: "Solomonska ostrva" },
  { code: "SOM", name: "Somalija" },
  { code: "ZAF", name: "Južnoafrička Republika" },
  { code: "SSD", name: "Južni Sudan" },
  { code: "ESP", name: "Španija" },
  { code: "LKA", name: "Šri Lanka" },
  { code: "SDN", name: "Sudan" },
  { code: "SUR", name: "Surinam" },
  { code: "SWE", name: "Švedska" },
  { code: "CHE", name: "Švajcarska" },
  { code: "SYR", name: "Sirija" },
  { code: "TWN", name: "Tajvan" },
  { code: "TJK", name: "Tadžikistan" },
  { code: "TZA", name: "Tanzanija" },
  { code: "THA", name: "Tajland" },
  { code: "TLS", name: "Istočni Timor" },
  { code: "TGO", name: "Togo" },
  { code: "TON", name: "Tonga" },
  { code: "TTO", name: "Trinidad i Tobago" },
  { code: "TUN", name: "Tunis" },
  { code: "TUR", name: "Turska" },
  { code: "TKM", name: "Turkmenistan" },
  { code: "UGA", name: "Uganda" },
  { code: "UKR", name: "Ukrajina" },
  { code: "ARE", name: "Ujedinjeni Arapski Emirati" },
  { code: "GBR", name: "Velika Britanija" },
  { code: "USA", name: "Sjedinjene Američke Države" },
  { code: "URY", name: "Urugvaj" },
  { code: "UZB", name: "Uzbekistan" },
  { code: "VUT", name: "Vanuatu" },
  { code: "VEN", name: "Venecuela" },
  { code: "VNM", name: "Vijetnam" },
  { code: "YEM", name: "Jemen" },
  { code: "ZMB", name: "Zambija" },
  { code: "ZWE", name: "Zimbabve" },
  { code: "XKX", name: "Kosovo" },
];

export function searchCountries(query: string): CountryEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length < 1) return [];
  return COUNTRIES.filter((c) => c.name.toLowerCase().includes(q) || c.code.toLowerCase() === q).slice(0, 8);
}

export function findCountryByCode(code: string): CountryEntry | null {
  const upper = code.trim().toUpperCase();
  return COUNTRIES.find((c) => c.code === upper) ?? null;
}
